export const FETCH_PREVIOUS_TASKS_SUCCESS = 'FETCH_PREVIOUS_TASKS_SUCCESS';
export const FETCH_CURRENT_TASKS = 'FETCH_CURRENT_TASKS';
export const FETCH_CURRENT_TASKS_SUCCESS = 'FETCH_CURRENT_TASKS_SUCCESS';
export const FETCH_CURRENT_TASKS_FAILURE = 'FETCH_CURRENT_TASKS_FAILURE';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
